spring:
  application:
    name: itoken-service-admin
  boot:
    admin:
      client:
        url: http://192.168.168.134:8084
  zipkin:
    base-url: http://192.168.168.134:9411
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

server:
  port: 8601

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.168.134:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info