spring:
  application:
    name: itoken-eureka
  boot:
    admin:
      client:
        url: http://192.168.168.134:8084
  zipkin:
    base-url: http://192.168.168.134:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.168.134:8761/eureka/,http://192.168.168.134:8861/eureka/,http://192.168.168.134:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info